# Generated by Django 2.1.2 on 2018-11-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='csv',
        ),
    ]
