# Generated by Django 2.1.2 on 2018-11-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20181102_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zid', models.CharField(max_length=5)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('Credit_card_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='csv',
        ),
    ]
